### ISSUE TITLE
verisign tld's no longer show registrant, etc info? Also exits with error code 1.

### ISSUE THREAD

**Issue by lilmike** [rfc1036/whois#54] opened 2017-07-26 06:17 UTC
Hey,
I just did a whois on several .com, .net domains, and each one showed only the registrar, dates, name servers, etc. In addition, whois exited with an error 1, as if the domain did not exist. Is this a change to verisign that breaks this tool? Is it not broken at all? In either case, any idea why no registrant, etc contact info is showing up?
-Michael.
P.S. whois version: 5.2.16-1 arch linux.

**Comment by lilmike** [comment] 2017-07-26 07:02
Update: It only happens on some domains -- example:
a11y.net -- broken, enom.
a11y.com -- broken, godaddy
registrar-servers.com -- working, also enom
Not sure what to make of some working and some not, even from the same registrar.
-Michael.

**Comment by rfc1036** [comment] 2017-07-26 08:32
I cannot reproduce this.

**Comment by hubandr** [comment] 2017-07-26 09:38
Some registries do not provide the complete information over their port 43 whois. Is there a redirect note in the response?

**Comment by lilmike** [comment] 2017-07-26 09:48
I kind of wonder if I'm being rate limited somehow, but I don't know why, as I've probably only done like 20-30 queries in the past 24 hours. It looks like this, and it's worth noting it seems kind of random, registrar-servers.com (which I tried somewhere in the middle of tests, after a11y.com/.net) now does it:

   Domain Name: MEOWMEOW.NET
   Registry Domain ID: 4840751_DOMAIN_NET-VRSN
   Registrar WHOIS Server: whois.networksolutions.com
   Registrar URL: http://networksolutions.com
   Updated Date: 2017-04-03T23:45:35Z
   Creation Date: 1999-03-31T05:00:00Z
   Registry Expiry Date: 2022-03-31T04:00:00Z
   Registrar: Network Solutions, LLC.
   Registrar IANA ID: 2
   Registrar Abuse Contact Email: abuse@web.com
   Registrar Abuse Contact Phone: +1.8003337680
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS11.WEBHOST8.COM
   Name Server: NS12.WEBHOST8.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2017-07-26T09:44:31Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated except as reasonably necessary to register domain names or
modify existing registrations; the Data in VeriSign Global Registry
Services' ("VeriSign") Whois database is provided by VeriSign for
information purposes only, and to assist persons in obtaining information
about or related to a domain name registration record. VeriSign does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to VeriSign (or its computer systems). The compilation,
repackaging, dissemination or other use of this Data is expressly
prohibited without the prior written consent of VeriSign. You agree not to
use electronic processes that are automated and high-volume to access or
query the Whois database except as reasonably necessary to register
domain names or modify existing registrations. VeriSign reserves the right
to restrict your access to the Whois database in its sole discretion to ensure
operational stability.  VeriSign may restrict or terminate your access to the
Whois database for failure to abide by these terms of use. VeriSign
reserves the right to modify these terms at any time.

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.

-Michael.

**Comment by lilmike** [comment] 2017-07-26 09:52
Ok, I think it must be something specific to either my computer or ip (like rate limiting). I just tried on two servers and they showed the normal info.
-Michael.

**Comment by lilmike** [comment] 2017-07-27 21:10
Actually, now I'm getting the same output on both servers I tried with. Could it be some kind of format change?
-Michael.

**Comment by rfc1036** [comment] 2017-07-27 21:14
Yes: fixed in the latest release. https://github.com/rfc1036/whois/pull/56

**Closed by rfc1036** 2017-07-27 21:14 UTC
