### ISSUE TITLE
whois command returns non-zero exit code

### ISSUE THREAD

**Issue by vsevoloddc** [rfc1036/whois#68] opened 2018-04-26 09:08 UTC
Hi! 
When I use whois command to find out when the domain (*.com) expires I must get the exit code 0, but i get exit code 1. When I use whois command for domain *.ru or *.org I get exit code 0. 
Because of non-zero code, I can not use the script to automatically check the validity period of a domain.
Can I somehow solve this problem?

```
nagios@webt:~$ whois --version
Vrsion 5.2.7.
```

```
nagios@webt:~$ whois vk.com; echo EXIT CODE: $?
   Domain Name: VK.COM
   Registry Domain ID: 3206186_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.nic.ru
   Registrar URL: http://nic.ru
   Updated Date: 2017-12-21T12:36:17Z
   Creation Date: 1997-06-24T04:00:00Z
   Registry Expiry Date: 2019-06-23T04:00:00Z
   Registrar: Regional Network Information Center, JSC dba RU-CENTER
   Registrar IANA ID: 463
   Registrar Abuse Contact Email: tld-abuse@nic.ru
   Registrar Abuse Contact Phone: +7 (495) 994-46-01
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS1.VKONTAKTE.RU
   Name Server: NS2.VKONTAKTE.RU
   Name Server: NS3.VKONTAKTE.RU
   Name Server: NS4.VKONTAKTE.RU
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2018-04-26T09:02:16Z <<<

*****************************************
TEXT
*****************************************
EXIT CODE: 1
```

```
nagios@webt:~$ whois netconfig.org; echo EXIT CODE: $?
Domain Name: NETCONFIG.ORG
Registry Domain ID: D159330187-LROR
Registrar WHOIS Server: whois.enom.com
Registrar URL: http://www.enom.com
Updated Date: 2017-05-31T15:43:26Z
Creation Date: 2010-06-02T21:15:31Z
Registry Expiry Date: 2018-06-02T21:15:31Z
Registrar Registration Expiration Date:
Registrar: eNom, Inc.
Registrar IANA ID: 48
Registrar Abuse Contact Email: abuse@enom.com
Registrar Abuse Contact Phone: +1.4252982646
Reseller:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferP
*****************************************
TEXT
*****************************************
EXIT CODE: 0
```

**Comment by glensc** [comment] 2018-04-27 12:06
@vsevoloddc upgrade first!

https://github.com/rfc1036/whois/releases

- v5.3.0  …
- v5.2.20  …

**Comment by rfc1036** [comment] 2018-05-01 08:17
Indeed, this has been caused by ICANN-mandated changes and has been fixed in a later release.

**Closed by rfc1036** 2018-05-01 08:17 UTC
